
sonar.projectKey=devsecops-flask-app
sonar.organization=
Key: 
sonar.host.url=https://sonarcloud.io


sonar.projectName=DevSecOps Flask Application
sonar.projectVersion=1.0.0


sonar.sources=backend
sonar.tests=backend/tests

sonar.test.inclusions=backend/tests/**/*.py


sonar.language=py
sonar.python.version=3.9


sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**,**/node_modules/**,**/migrations/**

sonar.sourceEncoding=UTF-8
