apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: devsecops-app
    environment: prod
data:
  APP_ENV: "production"
  APP_NAME: "DevSecOps Flask Application"
  DEBUG: "False"
  LOG_LEVEL: "WARNING"
