apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: devsecops-app
    environment: dev
data:
  APP_ENV: "development"
  APP_NAME: "DevSecOps Flask Application"
  DEBUG: "True"
  LOG_LEVEL: "DEBUG"
